language: node_js
sudo: enabled

services:
  - docker

install: cd client && yarn install && yarn build
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t ekofe-client client 
  - docker build -t ekofe-server server
  - docker images
  - docker tag ekofe-client $DOCKER_USERNAME/ekofe-client
  - docker tag ekofe-server $DOCKER_USERNAME/ekofe-server
  - docker push $DOCKER_USERNAME/ekofe-client
  - docker push $DOCKER_USERNAME/ekofe-server
