version: '2'
services:
  client:
    build: ./client
    ports:
      - 8080:80
    links:
      - server
  server:
    build: ./server
    ports:
      - 3001:3001
    links:
      - db
    environment:
      - SEED=547645382715487
      - DATA_DIR=/data
  db:
    image: redis:3.2-alpine
    volumes:
      - "./data:/data"
      