version: '2'
services:
  client:
    image: flash1293/ekofe-client
    ports:
      - 8080:8080
    links:
      - server
  server:
    image: flash1293/ekofe-server
    volumes:
      - "./data:/data"
    environment:
      - SEED=547645382715487
      - DATA_DIR=/data
